/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application")
}

dependencies {
    implementation(platform(libs.jackson.bom))
    implementation(libs.jackson.databind)
    implementation(libs.jackson.datatype.jdk8)
    implementation(libs.jackson.datatype.jsr310)
    implementation(libs.logbackClassic)

    implementation(libs.javalin.bundle)

    testImplementation(libs.assertj.core)
    testImplementation(libs.mockito.core)

    testFunctionalImplementation(libs.assertj.core)
    testFunctionalImplementation(libs.assertj.json.unit)
    testFunctionalImplementation(libs.restAssured)
    testFunctionalImplementation(libs.awaitility)

}

application {
    // Define the main class for the application.
    mainClass = "com.neverless.app.App"
}
